export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_PRODUCT_NULL = "SET_PRODUCT_NULL";
export const SHOW_ORDERS = "SHOW_ORDERS";
export const SELECT_ORDER_BY_ID="SELECT_ORDER_BY_ID";
export const DELETE_ORDER ='DELETE_ORDER'
